// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _SALOME_InteractiveObject_HeaderFile
#define _SALOME_InteractiveObject_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_SALOME_InteractiveObject_HeaderFile
#include <Handle_SALOME_InteractiveObject.hxx>
#endif

#ifndef _Standard_CString_HeaderFile
#include <Standard_CString.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif


class SALOME_InteractiveObject : public MMgt_TShared {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT   SALOME_InteractiveObject();
Standard_EXPORT   SALOME_InteractiveObject(const Standard_CString anEntry, 
					   const Standard_CString aComponentDataType,
					   const Standard_CString aName = "");
Standard_EXPORT   void setEntry(const Standard_CString anEntry) ;
Standard_EXPORT   Standard_CString getEntry() ;
Standard_EXPORT   void setName(const Standard_CString aName) ;
Standard_EXPORT   Standard_CString getName() ;
Standard_EXPORT   Standard_Boolean hasEntry() ;
Standard_EXPORT   virtual  Standard_Boolean isSame(const Handle(SALOME_InteractiveObject)& anIO) ;

Standard_EXPORT   Standard_Boolean hasReference() ;
Standard_EXPORT   Standard_CString getReference() ;
Standard_EXPORT   void setReference(const Standard_CString aReference) ;

Standard_EXPORT   void setComponentDataType(const Standard_CString ComponentDataType) ;
Standard_EXPORT   Standard_CString getComponentDataType() ;
Standard_EXPORT   Standard_Boolean isComponentType(const Standard_CString ComponentDataType) ;

Standard_EXPORT   ~SALOME_InteractiveObject();




 // Type management
 //
 Standard_EXPORT friend Handle_Standard_Type& SALOME_InteractiveObject_Type_();
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //
Standard_CString myReference;
Standard_CString myEntry;
Standard_CString myName;
Standard_CString myComponentDataType;

private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
