
pymodule_template = """\
# DO NOT EDIT THIS FILE!
#
# Python module @module@ generated by omniidl

import omnipatch
omnipatch.updateModule("@module@")

# ** 1. Stub files contributing to this module

# ** 2. Sub-modules

# ** 3. End"""

import omniidl_be.python
omniidl_be.python.pymodule_template=pymodule_template

def run(tree, args):
    omniidl_be.python.run(tree, args)

