#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2024  CEA, EDF
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

# -ex bt
# -x script.gdb
# -nx to skip .gdbinit

def GetRendezVous():
  import sys
  if len( sys.argv ) != 3:
      raise RuntimeError("salome_process_attach have to take a rendez-vous file and gdb script")
  return sys.argv[1],sys.argv[2]

import salome
salome.salome_init()
rdv,gdbfile = GetRendezVous()
remoteNS = salome.naming_service.LoadIORInFile(rdv)
remoteGlbs = salome.orb.string_to_object( remoteNS.Resolve("PID_TO_TRACK").decode() )
import pickle
pidToTrack = pickle.loads( remoteGlbs.getAttr("CTX0") )["pid"]
returncode, stdout, stderr = remoteGlbs.execute(["gdb","-batch","-x",gdbfile,"attach",str(pidToTrack)])
st = f"""returnCode = {returncode}
stdout = {stdout.decode()}
stderr = {stderr.decode()}
"""
print(st)
