
SET(LIBXML2_ROOT $ENV{LIBXML2_ROOT})
IF(LIBXML2_ROOT)
  FIND_PATH(LIBXML2_INCLUDE_DIR libxml/parser.h ${LIBXML2_ROOT}/include)
  FIND_LIBRARY(LIBXML2_LIBS libxml2 ${LIBXML2_ROOT}/lib)
ELSE(LIBXML2_ROOT)
  FIND_PATH(LIBXML2_INCLUDE_DIR libxml/parser.h /usr/include/libxml2)
  FIND_LIBRARY(LIBXML2_LIBS xml2 /usr/lib)
ENDIF(LIBXML2_ROOT)

SET(LIBXML2_INCLUDES -I${LIBXML2_INCLUDE_DIR})

SET(ICONV_ROOT $ENV{ICONV_ROOT})
IF(ICONV_ROOT)
  FIND_PATH(ICONV_INCLUDE_DIR iconv.h ${ICONV_ROOT}/include)
  FIND_LIBRARY(ICONV_LIBS iconv ${ICONV_ROOT}/lib)
  SET(LIBXML2_INCLUDES ${LIBXML2_INCLUDES} -I${ICONV_INCLUDE_DIR})
  SET(LIBXML2_LIBS ${LIBXML2_LIBS} ${ICONV_LIBS})
ENDIF(ICONV_ROOT)

SET(LIBXML_INCLUDES ${LIBXML2_INCLUDES})
SET(LIBXML_CPPFLAGS ${LIBXML2_INCLUDES})
SET(LIBXML_LIBS ${LIBXML2_LIBS})
