
# HDF5 detection for Salome

set(HDF5_ROOT_DIR $ENV{HDF5_ROOT_DIR} CACHE PATH "Path to Hdf5 directory")
if(EXISTS ${HDF5_ROOT_DIR})
  set(CMAKE_INCLUDE_PATH ${HDF5_ROOT_DIR}/include)
  set(CMAKE_LIBRARY_PATH ${HDF5_ROOT_DIR}/lib)
  set(CMAKE_PROGRAM_PATH ${HDF5_ROOT_DIR}/bin)
endif(EXISTS ${HDF5_ROOT_DIR})
find_package(HDF5 COMPONENTS C REQUIRED)
if (HDF5_FOUND)
  set(HDF5_DEFINITIONS "-DH5_USE_16_API ${HDF5_DEFINITIONS}" )
  if(WINDOWS)
    set(HDF5_DEFINITIONS "-D_HDF5USEDLL_ ${HDF5_DEFINITIONS}" )
  endif(WINDOWS)
endif(HDF5_FOUND)
