
SET(BOOST_ROOT $ENV{BOOST_ROOT})
IF(BOOST_ROOT)
  FIND_PATH(BOOST_INCLUDES boost/shared_ptr.hpp ${BOOST_ROOT})
  # FIND_LIBRARY(BOOST_LIBS boost_thread-vc80-mt-1_34_1 ${BOOST_ROOT}/lib)
  SET(BOOST_CPPFLAGS -I${BOOST_INCLUDES})
ENDIF(BOOST_ROOT)
