
# LIBBATCH detection for Salome

include(FindPackageHandleStandardArgs)

set(LIBBATCH_ROOT_DIR $ENV{LIBBATCH_ROOT_DIR} CACHE PATH "Path to libbatch directory")
if(EXISTS ${LIBBATCH_ROOT_DIR})
  find_package(libbatch QUIET CONFIG PATHS ${LIBBATCH_ROOT_DIR}/lib NO_DEFAULT_PATH)
endif(EXISTS ${LIBBATCH_ROOT_DIR})
find_package(libbatch QUIET CONFIG)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(libbatch DEFAULT_MSG
  LIBBATCH_ROOT_DIR LIBBATCH_INCLUDE_DIRS LIBBATCH_LIBRARIES
  LIBBATCH_RUNTIME_LIBRARY_DIRS LIBBATCH_PYTHONPATH)
