
IF(WINDOWS)
  FIND_PROGRAM(PYTHON_EXECUTABLE python_d)
ELSE(WINDOWS)
  FIND_PROGRAM(PYTHON_EXECUTABLE python)
ENDIF(WINDOWS)

SET(PYTHON_ROOT ${PYTHON_EXECUTABLE})
GET_FILENAME_COMPONENT(PYTHON_ROOT ${PYTHON_ROOT} PATH)
GET_FILENAME_COMPONENT(PYTHON_ROOT ${PYTHON_ROOT} PATH)

FIND_PATH(PYTHON_INCLUDE_PATH Python.h PATHS ${PYTHON_ROOT}/include ${PYTHON_ROOT}/include/python2.5)

IF(WINDOWS)
  FIND_LIBRARY(PYTHON_LIBRARIES python25_d ${PYTHON_ROOT}/libs)
ELSE(WINDOWS)
  FIND_LIBRARY(PYTHON_LIBRARIES python2.5 ${PYTHON_ROOT}/lib)
ENDIF(WINDOWS)

SET(PYTHON_INCLUDES -I${PYTHON_INCLUDE_PATH})
SET(PYTHON_LIBS ${PYTHON_LIBRARIES})

IF(WINDOWS)
  SET(PYTHON_VERSION python2.5)
ELSE(WINDOWS)
  GET_FILENAME_COMPONENT(PYTHON_VERSION ${PYTHON_INCLUDE_PATH} NAME)
ENDIF(WINDOWS)

IF(WINDOWS)
  SET(PYTHON_INCLUDES ${PYTHON_INCLUDES} -DHAVE_DEBUG_PYTHON)
ENDIF(WINDOWS)
