
SET(FULLDIR ${CMAKE_INSTALL_PREFIX}/${DIR})
FILE(MAKE_DIRECTORY ${FULLDIR})
MESSAGE(STATUS "Compiling ${IDL_FILE} into ${FULLDIR}")
EXECUTE_PROCESS(COMMAND ${OMNIORB_IDL_PYTHON} ${IDLPYFLAGS} -C${FULLDIR} ${CMAKE_CURRENT_SOURCE_DIR}/${IDL_FILE})
