#! /bin/sh
# Copyright (C) 2007-2016  CEA/DEN, EDF R&D, OPEN CASCADE
#
# Copyright (C) 2003-2007  OPEN CASCADE, EADS/CCR, LIP6, CEA/DEN,
# CEDRAT, EDF R&D, LEG, PRINCIPIA R&D, BUREAU VERITAS
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

chmodParams=""
dirParams=""
dirPath=""
args=""

while [ x"$1" != x ]; do
if test $# != "1"; then
case $1 in
-c) shift;
continue;;

-d) dirParams="yes"
shift;
continue;;

-m) shift;
chmodParams=$1
shift;
continue;;

*) args="$args $1"
shift;
continue;;
esac
else
dirPath=$1
fi
shift;
done

if test x$dirParams = "xyes"; then
mkdir -p $dirPath
else
cp -f $args $dirPath
for arg in $args; do
myArg=`basename $arg`
if test x$chmodParams != x; then
if test -d $dirPath; then
chmod $chmodParams $dirPath/$myArg
else
chmod $chmodParams $dirPath
fi
else
if test -d $dirPath; then
chmod a+x $dirPath/$myArg
else
chmod a+x $dirPath
fi
fi
done
fi

