//  Copyright (C) 2003  CEA/DEN, EDF R&D
//  
//  See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
//
//
//  File   : Logger.idl
//  Author : Vasily Rusyaev

#ifndef SALOME_LOGGER_IDL
#define SALOME_LOGGER_IDL

#pragma prefix "opencascade.com"

module SALOME_Logger 
{
	interface Logger 
	  {
	    //put message into one special place for all servers using Logger
	    oneway void putMessage (in string message);
            void ping (); 
	  };
};



#endif
